'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Eye,EyeOff,KeyRound,Layers,ShieldCheck,UserRound} from 'lucide-react';

type Props={onAuthenticated:()=>void};

export default function LoginScreen({onAuthenticated}:Props){
 const [configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
 useEffect(()=>{fetch('/api/auth/status',{cache:'no-store'}).then(async response=>{const result:any=await response.json();if(!response.ok)throw new Error(result.error);if(result.authenticated){onAuthenticated();return}setConfigured(Boolean(result.configured))}).catch(()=>{setConfigured(true);setError('No pudimos comprobar el acceso. Intenta nuevamente.')})},[onAuthenticated]);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget)) as Record<string,string>;
  if(!configured&&values.password!==values.confirm){setError('Las contraseñas no coinciden.');setBusy(false);return}
  try{const response=await fetch(configured?'/api/auth/login':'/api/auth/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:values.username,password:values.password})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo iniciar sesión.');onAuthenticated()}catch(reason){setError(reason instanceof Error?reason.message:'No se pudo iniciar sesión.')}finally{setBusy(false)}
 }
 return <main className="login-shell"><section className="login-side"><div className="login-brand"><span><Layers size={27}/></span>terra<b>lote</b><i/></div><div className="login-copy"><span className="login-kicker">CONTROL DE LOTIFICACIONES</span><h1>Tu inventario y tu equipo, en un solo lugar.</h1><p>Disponibilidad sincronizada para vendedores y secretaría, con expedientes protegidos según cada rol.</p></div><div className="login-security"><ShieldCheck size={20}/><span>Acceso privado y sesiones seguras</span></div></section><section className="login-panel"><div className="login-card">{configured===null?<div className="login-loading"><span className="login-spinner"/><p>Preparando acceso seguro…</p></div>:<><span className="login-icon"><KeyRound size={24}/></span><div className="login-heading"><span>{configured?'BIENVENIDO':'CONFIGURACIÓN INICIAL'}</span><h2>{configured?'Inicia sesión':'Crea tu cuenta propietaria'}</h2><p>{configured?'Ingresa el usuario y la contraseña que te asignó la persona propietaria.':'Esta cuenta será la única autorizada para crear vendedores y secretarias.'}</p></div><form onSubmit={submit}><label className="field"><span>Usuario</span><span className="login-input"><UserRound size={17}/><input name="username" autoComplete="username" minLength={2} maxLength={80} required placeholder="Nombre o correo" autoFocus/></span></label><label className="field"><span>Contraseña</span><span className="login-input"><KeyRound size={17}/><input name="password" type={show?'text':'password'} autoComplete={configured?'current-password':'new-password'} minLength={10} maxLength={128} required placeholder="Mínimo 10 caracteres"/><button type="button" className="login-eye" onClick={()=>setShow(!show)} aria-label={show?'Ocultar contraseña':'Mostrar contraseña'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label>{!configured&&<label className="field"><span>Confirmar contraseña</span><span className="login-input"><KeyRound size={17}/><input name="confirm" type={show?'text':'password'} autoComplete="new-password" minLength={10} maxLength={128} required placeholder="Repite la contraseña"/></span></label>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary full login-submit" disabled={busy}>{busy?'Comprobando…':configured?'Entrar a TerraLote':'Crear cuenta y continuar'}</button></form><p className="login-note"><ShieldCheck size={15}/>{configured?'Tus permisos se aplican automáticamente al entrar.':'Guarda estas credenciales: solo tú podrás administrar usuarios.'}</p></>}</div></section></main>
}
