'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Camera,Check,ChevronRight,ArrowLeft,LockKeyhole} from 'lucide-react';
import {Field,Dialog,Capture} from './form-ui';
import {customerFields,ageAt,validateCustomer} from '../lib/customer-form';
import {financingPolicy,paymentPlan,terms} from '../lib/finance';
const money=(n:number)=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'GTQ'}).format(n);
function Signature({label,onChange}:{label:string,onChange:(s:string)=>void}){const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false);function pos(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return [(e.clientX-r.left)*600/r.width,(e.clientY-r.top)*180/r.height]}
return <div className="signature"><label>{label}</label><canvas ref={ref} width="600" height="180" aria-label={label} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;const [x,y]=pos(e),c=e.currentTarget.getContext('2d')!;c.lineWidth=2.5;c.lineCap='round';c.strokeStyle='#174b3d';c.beginPath();c.moveTo(x,y)}} onPointerMove={e=>{if(!drawing.current)return;const [x,y]=pos(e),c=e.currentTarget.getContext('2d')!;c.lineTo(x,y);c.stroke()}} onPointerUp={e=>{drawing.current=false;onChange(e.currentTarget.toDataURL('image/png'))}} onPointerCancel={()=>{drawing.current=false}}/><button type="button" onClick={()=>{ref.current!.getContext('2d')!.clearRect(0,0,600,180);onChange('')}}>Borrar firma</button></div>}
export default function ReservationForm({lot,project,member,onClose,onSaved}:{lot:any,project:any,member:any,onClose:()=>void,onSaved:()=>void}){
 const [step,setStep]=useState(1),[values,setValues]=useState<Record<string,string>>({documentType:'DPI',monthlyIncome:'',otherIncome:'0',downPayment:String(financingPolicy.defaultDownPayment),months:'24'}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(''),[front,setFront]=useState<Blob|null>(null),[back,setBack]=useState<Blob|null>(null),[signatures,setSignatures]=useState({client:'',advisor:''});
 const urls=useMemo(()=>[front?URL.createObjectURL(front):'',back?URL.createObjectURL(back):''],[front,back]);useEffect(()=>()=>urls.forEach(u=>u&&URL.revokeObjectURL(u)),[urls]);
 const set=(key:string,value:string)=>setValues(v=>({...v,[key]:value}));let quote:ReturnType<typeof paymentPlan>|null=null;let quoteError='';try{quote=paymentPlan(lot.price,Number(values.downPayment),Number(values.months))}catch(e:any){quoteError=e.message}
 async function save(){setBusy(true);setError('');try{const customer=validateCustomer(values);if(!front||!back||!signatures.client||!signatures.advisor||!quote)throw new Error('Completa el formulario, las fotografías y las firmas.');const f=new FormData();Object.entries(customer).forEach(([k,v])=>f.set(k,String(v)));f.set('lotId',lot.id);f.set('months',values.months);f.set('downPayment',values.months==='0'?String(lot.price):values.downPayment);f.set('front',front,'anverso.jpg');f.set('back',back,'reverso.jpg');f.set('clientSignature',signatures.client);f.set('advisorSignature',signatures.advisor);const r=await fetch('/api/reserve',{method:'POST',body:f});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{throw new Error(text&&text!=='forbidden'?text:'No se pudo registrar la reservación. Verifica sesión y permisos.')}if(!r.ok)throw new Error(data?.error||text||'No se pudo registrar la reservación.');onSaved();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
const name=values.documentType==='Pasaporte'?'documento':'DPI';
const googleForm='https://docs.google.com/forms/d/e/1FAIpQLSeFwjpSbAFpP7BfFVQIVGzBiYkWsyCWw0L0d9niU7ixIFcpcw/viewform';
return <>{camera?<Capture side={camera} onClose={()=>setCamera('')} onCapture={(blob:Blob)=>{camera==='Anverso'?setFront(blob):setBack(blob);setCamera('')}}/>:<Dialog title={'Reservar '+lot.code+' · Las Azaleas'} onClose={()=>!busy&&onClose()} wide><div className="steps">{['Cliente','Compra','Documento','Firmas'].map((s,i)=><span key={s} className={step===i+1?'current':''}><b>{i+1}</b>{s}</span>)}</div><form onSubmit={e=>{e.preventDefault();setError('');try{if(step===1)validateCustomer(values);if(step===2&&!quote)throw new Error(quoteError);if(step===3&&(!front||!back))throw new Error('Captura ambos lados del documento.');if(step===4){save();return}setStep(step+1)}catch(e:any){setError(e.message)}}}>
{step===1&&<><p className="muted">Formulario Las Azaleas V.2025. Usa «No aplica» donde no corresponda y 0 si no hay otros ingresos.</p><p className="muted">Completa primero el <a href={googleForm} target="_blank" rel="noreferrer" className="text-blue-600 underline hover:text-blue-800">cuestionario de reservación en Google Forms</a> antes de continuar.</p>{['personal','laboral','referencias'].map((group,i)=><fieldset key={group}><legend>{['Datos del cliente','Información laboral','Referencias personales'][i]}</legend><div className="form-grid">{customerFields.filter(f=>f[3]===group).map(([key,label,type])=><Field key={key} label={label} type={type} required maxLength={500} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} max={type==='date'?new Date().toISOString().slice(0,10):undefined} value={values[key]||''} onChange={(e:any)=>set(key,e.target.value)}/>)}</div>{group==='personal'&&<><div className="form-grid"><label className="field"><span>Documento de identificación</span><select value={values.documentType} onChange={e=>set('documentType',e.target.value)}><option>DPI</option><option>Pasaporte</option></select></label><Field label={values.documentType==='DPI'?'Número de DPI (13 dígitos)':'Número de pasaporte'} required pattern={values.documentType==='DPI'?'[0-9]{13}':'[a-zA-Z0-9-]{5,30}'} value={values.dpi||''} onChange={(e:any)=>set('dpi',e.target.value)}/></div><button type="button" onClick={()=>setCamera('Anverso')} className="primary" style={{marginTop:'8px'}}><Camera size={16}/>Escanear DPI — abre cámara con marco redondeado</button>{values.birthDate&&<p className="muted">Edad: {ageAt(values.birthDate)} años</p>}</>}</fieldset>)}</>}
 {step===2&&<><div className="purchase-summary"><span>{project.name}</span><h3>Lote {lot.code}</h3><p>Manzana {lot.block||lot.code.replace(/[0-9-]/g,'')} · {lot.area} m²</p><strong>{money(lot.price)}</strong></div><div className="form-grid"><label className="field"><span>Plan de financiamiento</span><select value={values.months} onChange={e=>set('months',e.target.value)}><option value="0">Contado</option>{terms.map(m=><option key={m} value={m}>{m} meses · {m>=24?'14% anual':'Sin interés'}</option>)}</select></label><Field label={values.months==='0'?'Pago de contado (Q)':'Enganche (Q)'} type="number" min="0" max={lot.price} step="0.01" required disabled={values.months==='0'} value={values.months==='0'?lot.price:values.downPayment} onChange={(e:any)=>set('downPayment',e.target.value)}/></div>{quote?<div className="finance-summary"><div><span>Saldo a financiar</span><b>{money(quote.principal)}</b></div><div><span>Cuota mensual</span><b>{quote.months?money(quote.payment):'No aplica'}</b></div><div><span>Intereses del plan</span><b>{money(quote.totalInterest)}</b></div><div><span>Total con enganche</span><b>{money(quote.total)}</b></div>{quote.months>0&&<p>Cuota fija calculada sobre saldo. Tasa anual {quote.annualRate*100}%. Última cuota ajustada a {money(quote.lastPayment)} por redondeo.</p>}</div>:<p className="warning">{quoteError}</p>}<label className="field"><span>Integración de pagos</span><textarea required rows={3} maxLength={2000} placeholder="Forma de pago del enganche y acuerdos de pago" value={values.paymentIntegration||''} onChange={e=>set('paymentIntegration',e.target.value)}/></label><label className="field"><span>Observaciones</span><textarea rows={3} maxLength={2000} value={values.observations||''} onChange={e=>set('observations',e.target.value)}/></label><p className="muted">El precio se toma del catálogo. El servidor vuelve a verificar el precio y calcula el plan al confirmar.</p></>}
 {step===3&&<><p className="muted">Captura el anverso y reverso del {name}. {values.documentType==='Pasaporte'?'Para pasaporte, usa la página de identificación y la página de firma.':''} Revisa que los datos sean legibles.</p><div className="photo-grid">{['Anverso','Reverso'].map((side,i)=><button type="button" key={side} className="photo-card" onClick={()=>setCamera(side)}>{urls[i]?<img src={urls[i]} alt={side+' del documento'}/>:<Camera size={32}/>}<b>{side}</b><span>{urls[i]?'Volver a capturar':'Abrir cámara'}</span></button>)}</div><p className="detail-note"><LockKeyhole size={16}/>Las imágenes solo serán visibles para secretaría.</p></>}
 {step===4&&<><div className="review"><h3>{values.name}</h3><p>{values.documentType}: {values.dpi}</p><p>{project.name} · {lot.code}</p><p>{quote?.months?`${quote.months} meses · ${money(quote.payment)} al mes`:'Compra de contado'}</p><p>Vendedor: {member.name}</p></div><p className="muted">Firma con el dedo, lápiz o mouse en cada recuadro. Las firmas se guardarán junto al expediente.</p><Signature label="Firma del cliente" onChange={s=>setSignatures(v=>({...v,client:s}))}/><Signature label="Firma del vendedor" onChange={s=>setSignatures(v=>({...v,advisor:s}))}/></>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" disabled={busy} onClick={()=>step===1?onClose():setStep(step-1)}><ArrowLeft size={16}/>{step===1?'Cancelar':'Atrás'}</button><button className="primary" disabled={busy||(step===2&&!quote)||(step===3&&(!front||!back))||(step===4&&(!signatures.client||!signatures.advisor))}>{busy?'Registrando…':step===4?'Confirmar reservación':'Continuar'}{step===4?<Check size={16}/>:<ChevronRight size={16}/>}</button></div></form></Dialog>}</>
}
export function CustomerDetails({details,clientId}:{details:any,clientId:string}){if(!details)return null;let d:any;try{d=typeof details==='string'?JSON.parse(details):details}catch{return <p>No se pudo leer el expediente ampliado.</p>}return <div className="extended-record"><h3>Formulario del cliente</h3><dl>{customerFields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{d.customer?.[key]||'—'}</dd></div>)}</dl><h3>Condiciones de compra</h3><dl><div><dt>Precio registrado</dt><dd>{money(d.plan.price)}</dd></div><div><dt>Enganche</dt><dd>{money(d.plan.downPayment)}</dd></div><div><dt>Plazo</dt><dd>{d.plan.months?d.plan.months+' meses':'Contado'}</dd></div><div><dt>Cuota mensual</dt><dd>{money(d.plan.payment)}</dd></div><div><dt>Tasa anual</dt><dd>{d.plan.annualRate*100}%</dd></div><div><dt>Total con intereses</dt><dd>{money(d.plan.total)}</dd></div><div><dt>Integración de pagos</dt><dd>{d.customer.paymentIntegration}</dd></div><div><dt>Observaciones</dt><dd>{d.customer.observations||'Sin observaciones'}</dd></div></dl><div className="photo-grid">{['clientSignature','advisorSignature'].map((s,i)=><div key={s}><img className="document" src={'/api/file?reservation='+clientId+'&side='+s} alt={i?'Firma del vendedor':'Firma del cliente'}/><p>{i?'Firma del vendedor':'Firma del cliente'}</p></div>)}</div>{d.plan.schedule.length>0&&<details><summary>Ver plan de cuotas</summary><div className="schedule-table"><table><thead><tr><th>Mes</th><th>Cuota</th><th>Interés</th><th>Capital</th><th>Saldo</th></tr></thead><tbody>{d.plan.schedule.map((r:any)=><tr key={r.month}><td>{r.month}</td><td>{money(r.payment)}</td><td>{money(r.interest)}</td><td>{money(r.capital)}</td><td>{money(r.balance)}</td></tr>)}</tbody></table></div></details>}</div>}
