export const customerFields=[
 ['name','Nombre completo','text','personal'],['address','Domicilio','text','personal'],['homePhone','Teléfono de residencia (o No aplica)','text','personal'],['phone','Celular','tel','personal'],['nit','NIT (o CF)','text','personal'],['birthDate','Fecha de nacimiento','date','personal'],['nationality','Nacionalidad','text','personal'],['civilStatus','Estado civil','text','personal'],['occupation','Profesión u oficio','text','personal'],['email','Correo electrónico (o No aplica)','text','personal'],
 ['employer','Empresa donde trabaja (o No aplica)','text','laboral'],['workAddress','Dirección de trabajo (o No aplica)','text','laboral'],['workPhone','Teléfono de trabajo (o No aplica)','text','laboral'],['position','Puesto que desempeña (o No aplica)','text','laboral'],['monthlyIncome','Ingreso mensual (Q)','number','laboral'],['otherIncome','Otros ingresos mensuales (Q)','number','laboral'],
 ['reference1','Primera referencia personal','text','referencias'],['referencePhone1','Teléfono de primera referencia','tel','referencias'],['reference2','Segunda referencia personal','text','referencias'],['referencePhone2','Teléfono de segunda referencia','tel','referencias'],
] as const;
export type CustomerRecord=Record<string,string|number>&{name:string;address:string;phone:string;dpi:string;documentType:string;age:number;observations:string;paymentIntegration:string};
export function ageAt(date:string,today=new Date().toISOString().slice(0,10)){const birth=new Date(date+'T12:00:00Z'),now=new Date(today+'T12:00:00Z');return now.getUTCFullYear()-birth.getUTCFullYear()-(now.getUTCMonth()<birth.getUTCMonth()||(now.getUTCMonth()===birth.getUTCMonth()&&now.getUTCDate()<birth.getUTCDate())?1:0)}
export function validateCustomer(input:Record<string,unknown>):CustomerRecord{const out:Record<string,string>={};for(const [key,label,type] of customerFields){const v=input[key];if(typeof v!=='string'||!v.trim()||v.length>500)throw new Error('Completa: '+label);out[key]=v.trim();if(type==='number'&&(!Number.isFinite(Number(v))||Number(v)<0))throw new Error('Revisa: '+label);}
 for(const k of ['phone','referencePhone1','referencePhone2'])if(!/^\+?[\d ()-]{8,20}$/.test(out[k]))throw new Error('Revisa los números de teléfono.');
 if(!/^\d{4}-\d{2}-\d{2}$/.test(out.birthDate)||Number.isNaN(Date.parse(out.birthDate))||new Date(out.birthDate).toISOString().slice(0,10)!==out.birthDate||ageAt(out.birthDate)<0||ageAt(out.birthDate)>120)throw new Error('Revisa la fecha de nacimiento.');
 if(out.email.toLowerCase()!=='no aplica'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(out.email))throw new Error('Escribe un correo válido o No aplica.');
 if(!['DPI','Pasaporte'].includes(String(input.documentType)))throw new Error('Selecciona DPI o pasaporte.');
 const doc=String(input.dpi||'').trim();if(input.documentType==='DPI'?!/^\d{13}$/.test(doc):!/^[a-zA-Z0-9-]{5,30}$/.test(doc))throw new Error('Revisa el número del documento.');
 return {...out,dpi:doc,documentType:String(input.documentType),age:ageAt(out.birthDate),observations:String(input.observations||'').slice(0,2000),paymentIntegration:String(input.paymentIntegration||'').slice(0,2000)} as CustomerRecord;
}
